name: papertrail
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi
    - uvicorn
    - tortoise-orm
    - aiosqlite
    - pytest
    - pytest-asyncio
    - httpx
    - numpy
    - sentence-transformers